hold('off');

fill([x_star(:,2); flipud(x_star(:,2))], ...
     [       f_star_mean + 2 * sqrt(f_star_variance); ...
      flipud(f_star_mean - 2 * sqrt(f_star_variance))], ...
     [0.9, 0.9, 1], ...
     'edgecolor', 'none');

hold('on');

plot(x_star(:,2), y_star, 'r.');
plot(x(:,2), y, 'k+');
plot(x_star(:,2), f_star_mean, '-', ...
     'color', [0, 0, 0.8]);

axis([-10, 10, -4, 6]);
set(gca, 'tickdir', 'out', ...
         'box',     'off');
